[package]
name = "gacp-cli"
version = "0.1.0"
edition = "2021"
authors = ["GACP Team"]
description = "Git-Based Agent Context Protocol CLI"
license = "MIT"
repository = "https://github.com/your-org/gacp-cli"
keywords = ["git", "ai", "context", "yaml", "protocol"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.4", features = ["derive"] }
git2 = "0.18"
anyhow = "1.0"
walkdir = "2.4"
regex = "1.10"

# Additional utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6", features = ["v4", "serde"] }
colored = "2.0"
indicatif = "0.17"
thiserror = "1.0"
toml = "0.8"
pathdiff = "0.2"
validator = { version = "0.16", features = ["derive"] }
lazy_static = "1.4"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.8"
assert_fs = "1.1"
predicates = "3.0"

[[bin]]
name = "gacp"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true 