version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - actix
  - beforeunload
  - catthehacker
  - checkpointing
  - chrono
  - cpus
  - dashmap
  - hnsw
  - iconify
  - kitdocs
  - LOCOMO
  - mathjax
  - metadatas
  - minmax
  - onclick
  - Qdrant
  - reqwest
  - Segoe
  - serde
  - shiki
  - svelteness
  - Syneidesis
  - Tahoma
  - thiserror
  - unplugin
  - Verdana
  - vite
  - vitest
ignoreWords: []
import: []
