site_name: Rhema Documentation
site_description: Comprehensive documentation for the Rhema project
site_author: Rhema Team
site_url: https://rhema-ai.github.io/

# Repository
repo_name: rhema-ai/rhema
repo_url: https://github.com/rhema-ai/rhema
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Workspace Quick Start: getting-started/workspace-quick-start.md
    - Refactoring to Workspace: getting-started/refactoring-to-workspace.md
  - User Guide:
    - CLI Command Reference: user-guide/cli-command-reference.md
    - Configuration Management: user-guide/configuration-management.md
    - Batch Operations: user-guide/batch-operations.md
    - Interactive Mode: user-guide/interactive-mode.md
    - Performance Monitoring: user-guide/performance-monitoring.md
    - Conflict Resolution: user-guide/conflict-resolution.md
    - Enhanced Dependencies Command: user-guide/enhanced-dependencies-command.md
    - Enhanced Validation Command: user-guide/enhanced-validation-command.md
    - Lock File Health Checks: user-guide/lock-file-health-checks.md
  - Core Features:
    - Overview: core-features/README.md
    - Lock Configuration System: core-features/lock-configuration-system.md
    - Lock File Cache System: core-features/lock-file-cache-system.md
    - Lock File AI Integration: core-features/lock-file-ai-integration.md
    - CI/CD Lock File Integration: core-features/ci-cd-lock-file-integration.md
    - AI Service Lock File Enhancement: core-features/ai-service-lock-file-enhancement.md
    - Conflict Resolver Usage: core-features/conflict-resolver-usage.md
  - Reference:
    - Global Config Reference: reference/global-config-reference.md
    - Specification Schema Examples: reference/specification-schema-examples.md
  - Development Setup:
    - Development Overview: development-setup/development.md
    - Local Setup: development-setup/development/local-setup.md
    - Rust Setup: development-setup/development/rust-setup.md
    - Git Setup: development-setup/development/git-setup.md
    - Editor Setup:
      - VS Code: development-setup/editor-setup/vscode.md
      - Cursor: development-setup/editor-setup/cursor.md
      - IntelliJ: development-setup/editor-setup/intellij.md
      - Sublime Text: development-setup/editor-setup/sublime.md
      - Vim: development-setup/editor-setup/vim.md
    - CI/CD:
      - GitHub Actions: development-setup/development/cicd/github-actions.md
      - Local Pipeline Execution: development-setup/development/cicd/local-pipeline-execution.md
      - Pull Request Pipeline: development-setup/development/cicd/pull-request-pipeline.md
  - Architecture:
    - Overview: architecture/README.md
    - Proposals:
      - MCP Daemon Implementation: architecture/proposals/0001-mcp-daemon-implementation.md
      - Task Scoring Agentic Development: architecture/proposals/0002-task-scoring-agentic-development.md
      - Locomo Benchmarks Integration: architecture/proposals/0003-locomo-benchmarks-integration.md
      - Action Protocol Integration: architecture/proposals/0005-action-protocol-integration.md
      - Enhanced Dependency Management: architecture/proposals/0006-enhanced-dependency-management.md
      - Rhema Lock File System: architecture/proposals/0006-rhema-lock-file-system.md
      - Advanced AI Context Bootstrapping: architecture/proposals/0007-advanced-ai-context-bootstrapping.md
      - Enhanced Validation Compliance: architecture/proposals/0008-enhanced-validation-compliance.md
      - Enhanced Monitoring Observability: architecture/proposals/0009-enhanced-monitoring-observability.md
      - RAG Integration: architecture/proposals/0010-rag-integration.md
      - MCP Update Prompts: architecture/proposals/0011-mcp-update-prompts.md
      - Rhema MCP Strategic Recommendations: architecture/proposals/0011-rhema-mcp-strategic-recommendations.md
      - Rhema Enhancement Todo Tracking: architecture/proposals/0012-rhema-enhancement-todo-tracking.md
      - Prompt Pattern Advanced Features: architecture/proposals/0013-prompt-pattern-advanced-features.md
      - Embedded LLM Integration: architecture/proposals/0014-embedded-llm-integration.md
      - AST Action Hooks: architecture/proposals/0015-ast-action-hooks.md
      - Prompts AST: architecture/proposals/0015-prompts-ast.md
      - Rhema Cache Directory System: architecture/proposals/0016-rhema-cache-directory-system.md
      - Multi Agent Coordination Monitoring: architecture/proposals/0017-multi-agent-coordination-monitoring.md
      - CRDT Applications in Rhema: architecture/proposals/0018-crdt-applications-in-rhema.md
    - MCP Documentation:
      - MCP Overview: architecture/mcp/README.md
      - MCP Daemon API: architecture/mcp/mcp-daemon-api.md
      - MCP Daemon Config: architecture/mcp/mcp-daemon-config.md
      - MCP Daemon Deployment: architecture/mcp/mcp-daemon-deployment.md
      - MCP Daemon Quick Reference: architecture/mcp/mcp-daemon-quick-reference.md
      - MCP Daemon Usage: architecture/mcp/mcp-daemon-usage.md
  - Examples:
    - Overview: examples/README.md
    - Advanced Usage: examples/advanced-usage.md
    - CQL Queries: examples/cql-queries.md
    - E-commerce Epic Orchestration: examples/ecommerce-epic-orchestration.md
    - Enhanced Context Injection: examples/enhanced-context-injection.md
    - Implicit to Explicit Knowledge: examples/implicit-to-explicit-knowledge.md
    - Lock File Operations: examples/lock-file-operations.md
    - Prompt Chain Persistence: examples/prompt-chain-persistence.md
    - Prompt Effectiveness Tracking: examples/prompt-effectiveness-tracking.md
    - Prompt Versioning: examples/prompt-versioning.md
    - Query Provenance: examples/query-provenance.md
    - Template Management: examples/template-management.md
    - Quick Start Commands: examples/quick-start-commands.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      anchorlink: true
      permalink: true
      title: On this page

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Copyright
copyright: Copyright &copy; 2024 Rhema Team 