packages:
  # Rust crates (for reference, not managed by pnpm)
  - 'crates/*'
  
  # Documentation site
  - 'docs'
  
  # Editor plugins
  - 'editor-plugins/vscode'
  - 'editor-plugins/language-server'
  - 'editor-plugins/intellij'
  
  # Examples and other Node.js projects
  - 'examples/*'
  - 'kitdocs-docs' 