# Mimir configuration for Rhema
# Minimal configuration for metrics storage with Prometheus compatibility

multitenancy_enabled: false

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

compactor:
  sharding_ring:
    kvstore:
      store: memberlist

store_gateway:
  sharding_ring:
    kvstore:
      store: memberlist

ruler:
  ring:
    kvstore:
      store: memberlist

alertmanager:
  sharding_ring:
    kvstore:
      store: memberlist

# Storage configuration
common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/mimir

# Limits for single-tenant setup
limits:
  max_global_series_per_user: 1000000
  max_global_series_per_metric: 100000
  ingestion_rate: 10000
  ingestion_burst_size: 20000

# Server configuration
server:
  http_listen_port: 9009
  grpc_listen_port: 9095

# Logging
log_level: info 