[package]
name = "syneidesis-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Core types and utilities for the Syneidesis coordination ecosystem"
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Serialization
serde.workspace = true
serde_json.workspace = true

# Time handling
chrono.workspace = true

# Error handling
thiserror.workspace = true

# UUID generation
uuid.workspace = true

# Logging
tracing.workspace = true

# Async traits
async-trait = "0.1"

# Random number generation
rand = "0.8"

# Async runtime
tokio = { workspace = true, features = ["time", "macros"] }

[dev-dependencies]
tempfile = "3.8"
serde_test = "0.9" 