[package]
version = "0.1.0"
edition = "2021"
description = "Shared traits for Rhema action tools"
license = "Apache-2.0"

[dependencies]
async-trait = "0.1"
rhema-action-tool = { path = "../../rhema-action-tool" } 